import { MetaAstSchema, MetaAstFunc } from '../types';
import { SemanticNormalizer } from '../normalization/normalizer';
import { NormalizedSemanticType, SemanticKind, LANGUAGE_MAPPINGS } from '../normalization/types';

/**
 * Generates TypeScript Definition files (.d.ts) from semantic metadata.
 */
export class DtsGenerator {
  private normalizer = new SemanticNormalizer();
  private interfaces: Set<string> = new Set();
  private interfaceDefinitions: string[] = [];

  public generate(schema: MetaAstSchema): string {
    this.interfaces.clear();
    this.interfaceDefinitions = [];

    let functionStubs = '';
    schema.funcs.forEach(func => {
      functionStubs += this.generateFunctionStub(func);
    });

    let output = '/**\n';
    output += ' * @generated by meta-ast-stub-prototype\n';
    output += ' * @source meta-ast semantic metadata\n';
    output += ' * Do not edit manually.\n';
    output += ' */\n\n';

    if (this.interfaceDefinitions.length > 0) {
      output += '// --- Interfaces ---\n\n';
      output += this.interfaceDefinitions.join('\n\n') + '\n\n';
    }

    output += '// --- Functions ---\n\n';
    output += functionStubs;

    return output;
  }

  private generateFunctionStub(func: MetaAstFunc): string {
    let stub = '';
    
    if (func.docstring) {
      stub += `/**\n * ${func.docstring}\n */\n`;
    }

    const args = func.args
      .map(arg => `${arg.name}: ${this.resolveTsType(this.normalizer.normalize(arg.type), arg.name)}`)
      .join(', ');

    const normalizedRet = this.normalizer.normalize(func.ret);
    const retType = this.resolveTsType(normalizedRet, `${func.name}Result`);

    stub += `export function ${func.name}(${args}): ${retType};\n\n`;
    
    return stub;
  }

  private resolveTsType(type: NormalizedSemanticType, contextName: string): string {
    switch (type.kind) {
      case SemanticKind.String:
      case SemanticKind.Numeric:
      case SemanticKind.Boolean:
      case SemanticKind.Any:
        return LANGUAGE_MAPPINGS.typescript[type.kind];
      
      case SemanticKind.Array:
        return `${this.resolveTsType(type.elementType!, contextName)}[]`;
      
      case SemanticKind.Optional:
        return `${this.resolveTsType(type.innerType!, contextName)} | undefined`;
      
      case SemanticKind.Object:
        const interfaceName = this.capitalize(contextName);
        if (!this.interfaces.has(interfaceName)) {
          this.interfaces.add(interfaceName);
          let def = `export interface ${interfaceName} {\n`;
          for (const [key, val] of Object.entries(type.properties || {})) {
            const isOptional = false; // Simplified
            def += `  ${key}${isOptional ? '?' : ''}: ${this.resolveTsType(val, key)};\n`;
          }
          def += `}`;
          this.interfaceDefinitions.push(def);
        }
        return interfaceName;

      default:
        return 'any';
    }
  }

  private capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}

