import { MetaAstSchema, MetaAstFunc } from '../types';
import { getTsType } from '../mappings/typeMappings';

/**
 * Generates TypeScript Definition files (.d.ts) from semantic metadata.
 */
export class DtsGenerator {
  public generate(schema: MetaAstSchema): string {
    let output = '/**\n';
    output += ' * @generated by meta-ast-stub-prototype\n';
    output += ' * @source meta-ast semantic metadata\n';
    output += ' * Do not edit manually.\n';
    output += ' */\n\n';

    schema.funcs.forEach(func => {
      output += this.generateFunctionStub(func);
    });

    return output;
  }

  private generateFunctionStub(func: MetaAstFunc): string {
    let stub = '';
    
    // Generate JSDoc if docstring is present
    if (func.docstring) {
      stub += `/**\n * ${func.docstring}\n */\n`;
    }

    const args = func.args
      .map(arg => `${arg.name}: ${getTsType(arg.type)}`)
      .join(', ');

    const retType = getTsType(func.ret.type);

    stub += `declare function ${func.name}(${args}): ${retType};\n\n`;
    
    return stub;
  }
}
