import { MetaAstSchema, MetaAstFunc } from '../types';
import { getPyType } from '../mappings/typeMappings';

/**
 * Generates Python Type Stubs (.pyi) from semantic metadata.
 */
export class PyiGenerator {
  public generate(schema: MetaAstSchema): string {
    let output = '"""\n';
    output += '@generated by meta-ast-stub-prototype\n';
    output += '@source meta-ast semantic metadata\n';
    output += 'Do not edit manually.\n';
    output += '"""\n\n';
    output += 'from typing import Any\n\n';

    schema.funcs.forEach(func => {
      output += this.generateFunctionStub(func);
    });

    return output;
  }

  private generateFunctionStub(func: MetaAstFunc): string {
    let stub = '';

    const args = func.args
      .map(arg => `${arg.name}: ${getPyType(arg.type)}`)
      .join(', ');

    const retType = getPyType(func.ret.type);

    stub += `def ${func.name}(${args}) -> ${retType}: ...\n`;
    
    // Generate docstring in Python style
    if (func.docstring) {
      stub += `    """${func.docstring}"""\n`;
    }
    
    stub += '\n';
    return stub;
  }
}
