import { MetaAstSchema, MetaAstFunc } from '../types';
import { SemanticNormalizer } from '../normalization/normalizer';
import { NormalizedSemanticType, SemanticKind, LANGUAGE_MAPPINGS } from '../normalization/types';

/**
 * Generates Python Type Stubs (.pyi) from semantic metadata.
 */
export class PyiGenerator {
  private normalizer = new SemanticNormalizer();
  private typedDicts: Set<string> = new Set();
  private typedDictDefinitions: string[] = [];

  public generate(schema: MetaAstSchema): string {
    this.typedDicts.clear();
    this.typedDictDefinitions = [];

    let functionStubs = '';
    schema.funcs.forEach(func => {
      functionStubs += this.generateFunctionStub(func);
    });

    let output = '"""\n';
    output += '@generated by meta-ast-stub-prototype\n';
    output += '@source meta-ast semantic metadata\n';
    output += 'Do not edit manually.\n';
    output += '"""\n\n';
    output += 'from typing import Any, List, Optional, TypedDict\n\n';

    if (this.typedDictDefinitions.length > 0) {
      output += '# --- Type Definitions ---\n\n';
      output += this.typedDictDefinitions.join('\n\n') + '\n\n';
    }

    output += '# --- Functions ---\n\n';
    output += functionStubs;

    return output;
  }

  private generateFunctionStub(func: MetaAstFunc): string {
    let stub = '';

    const args = func.args
      .map(arg => `${arg.name}: ${this.resolvePyType(this.normalizer.normalize(arg.type), arg.name)}`)
      .join(', ');

    const normalizedRet = this.normalizer.normalize(func.ret);
    const retType = this.resolvePyType(normalizedRet, `${func.name}Result`);

    stub += `def ${func.name}(${args}) -> ${retType}: ...\n`;
    
    if (func.docstring) {
      stub += `    """${func.docstring}"""\n`;
    }
    
    stub += '\n';
    return stub;
  }

  private resolvePyType(type: NormalizedSemanticType, contextName: string): string {
    switch (type.kind) {
      case SemanticKind.String:
      case SemanticKind.Numeric:
      case SemanticKind.Boolean:
      case SemanticKind.Any:
        return LANGUAGE_MAPPINGS.python[type.kind];
      
      case SemanticKind.Array:
        return `List[${this.resolvePyType(type.elementType!, contextName)}]`;
      
      case SemanticKind.Optional:
        return `Optional[${this.resolvePyType(type.innerType!, contextName)}]`;
      
      case SemanticKind.Object:
        const dictName = this.capitalize(contextName);
        if (!this.typedDicts.has(dictName)) {
          this.typedDicts.add(dictName);
          let def = `class ${dictName}(TypedDict):\n`;
          const entries = Object.entries(type.properties || {});
          if (entries.length === 0) {
            def += `    pass`;
          } else {
            for (const [key, val] of entries) {
              def += `    ${key}: ${this.resolvePyType(val, key)}\n`;
            }
          }
          this.typedDictDefinitions.push(def);
        }
        return dictName;

      default:
        return 'Any';
    }
  }

  private capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}

